import os

"""
Original dataset:

─ 2d3d_dataset
    ├─ .mask (the masks in the intraoperative views)
    │   ├─ mask1.png
    │   └─ ...
    ├─ restrictions.json (speicifies the prior-knowledge restricted area of each type)
    ├─ case 0 
    │   ├─ label (for evaluation)
    │   │   ├─ 00001.png
    │   │   └─ ...
    │   ├─ orig.nii.gz (preoperative view, segmented ct volume)
    │   ├─ clip.mp4 (intraoperative view, laparoscopic video)
    │   ├─ prior.json (specifies which type this case belongs to)
    │   ├─ ** mesh.gltf (will be generated by `prepare_dataset.py`) **
    │   ├─ ** 00001.png (will be generated by `prepare_dataset.py`) **
    │   └─ ...
    └─ ...
    
"""

DATASET_DIR = '../2d3d_dataset'
ALL_CASES = [d for d in os.listdir(DATASET_DIR)
             if os.path.isdir(os.path.join(DATASET_DIR, d))
             and not d.startswith('.')]
ALL_CASES.sort()
MASK_DIR = os.path.join(DATASET_DIR, '.mask')
RESTRICTIONS_INFO_PATH = os.path.join(DATASET_DIR, 'restrictions.json')
PREOPERATIVE_FILENAME = 'orig.nii.gz'
INTRAOPERATIVE_FILENAME = 'clip.mp4'
PRIOR_INFO_FILENAME = 'prior.json'
MESH_FILENAME = 'mesh.gltf'
WEIGHTS_DIR = 'weights'
RESULTS_DIR = 'results'
PROBE_FILENAME = 'probes.npz'
TEST_DATA_DIR = 'test_data'
